### ISSUE TITLE
Conflict with another mod

### ISSUE THREAD

**Issue by Sir-AJ** [Faeryn/OutwardWeaponSkillKeys#1]
I'd love to try your mod but it must conflict with extra quick keys or multiple quickslot bars because game will not load after I install your mod. I'll try and figure out exactly which mod is incompatible;e with yours.  I deleted both and it still did not load game. I'll try some others

Could not get it to work

**Comment by Faeryn** [comment]
Hello! Please send me your BepInEx log file. It should be in `%AppData%\r2modmanPlus-local\Outward\profiles\Default\BepInEx\LogOutput.log` on Windows (substitute the Default profile with whatever profile you are using. Additionally, r2modman folder might be different).
If you don't want to or can't, then send me the list of your active mods.

**Comment by Sir-AJ** [comment]
This is a brand new game, on a fresh profile, with only a few mods.
--------------------------------
[output_log.txt](https://github.com/Faeryn/OutwardWeaponSkillKeys/files/8008637/output_log.txt)

**Comment by Faeryn** [comment]
Thank you, I published a version (1.1.1) that fixes this issue in Thunderstore.
